### ISSUE TITLE
Unclear which onnx file to get from Pinto_model_zoo

### ISSUE THREAD

**Issue by surak** [ibaiGorordo/ONNX-YOLOv7-Object-Detection#1]
You mention to download the onnx files from https://github.com/PINTO0309/PINTO_model_zoo/tree/main/307_YOLOv7 , but I see a bunch of "nms_yolov7_10080.onnx" and so files there, and it's not clear at all which one would work. Any hints on how to get it to run?

Thanks

**Comment by ibaiGorordo** [comment]
I think he has added some new models, but probably any of the models of the single batch groups should work (both the ones with and without postprocessing included)

**Comment by surak** [comment]
Ok, thanks for the info. I am able to use YoloV7 on a Raspberry Pi with reasonable performance by

- calling https://github.com/PINTO0309/PINTO_model_zoo/blob/main/307_YOLOv7/download_single_batch.sh
- adding the `yolov7-tiny_480x640.onnx` to the `webcam_object_detection.py`
- The `post`processed` one didn't work, with the same size. I didn't try any other files.

**Comment by ibaiGorordo** [comment]
Thanks for the changes. What error did you get? In my case, it runs fine on a computer, so it might have to do with the fact that it is running on a Raspberry Pi.

On that note, if you want to run the model in the raspberry pi, my code might not be that well optimized there and you can probably get some increase on speed if you optimize it. Also, it might also run faster in another framework like Tensorflow Lite.

**Comment by surak** [comment]
About the "post", it's probably something trivial, but I don't know:

```python
Traceback (most recent call last):
  File "/home/surak/Devel/bird/ONNX-YOLOv7-Object-Detection/webcam_object_detection.py", line 31, in <module>
    boxes, scores, class_ids = yolov7_detector(frame)
  File "/home/surak/Devel/bird/ONNX-YOLOv7-Object-Detection/YOLOv7/YOLOv7.py", line 19, in __call__
    return self.detect_objects(image)
  File "/home/surak/Devel/bird/ONNX-YOLOv7-Object-Detection/YOLOv7/YOLOv7.py", line 39, in detect_objects
    self.boxes, self.scores, self.class_ids = self.parse_processed_output(outputs)
  File "/home/surak/Devel/bird/ONNX-YOLOv7-Object-Detection/YOLOv7/YOLOv7.py", line 112, in parse_processed_output
    class_ids = predictions[:, 1]
IndexError: index 1 is out of bounds for axis 1 with size 1
```

About performance, I'm getting about 1.6fps with a 640x384 yolo tiny, and 0.23fps with yolov7-384-640.

I'm happy with it for now, as it does what I want from it. Thanks!
