### ISSUE TITLE
cannot import name 'YOLOv7' from 'yolov7'

### ISSUE THREAD

**Issue by EM7097** [ibaiGorordo/ONNX-YOLOv7-Object-Detection#10]
I am a new player. These questions may be stupid. Sorry for that. 

As the repo said I git clone the repo and down load the yolov7_Nx3x256x320.onnx 
 
and try to run the python file all of the 3 detection files do not work and give this error.

Thanks in advance for the help

**Comment by EM7097** [comment]
btw. I install the yolov7 by "pip install yolov7" and modified the path of the onnx file 
I use a window system and Nvidia GPU

**Comment by kendrick90** [comment]
The pip yolov7 package is empty and is not what you need. The solution for this is to use "from YOLOv7...." instead of "from yolov7..." this change needs to be made in multiple places.

**Comment by ibaiGorordo** [comment]
My bad, I changed the name of the folder, but git didn't get the changes. I think it should be fine now.

**Comment by EM7097** [comment]
Thanks so much I will try it today.

**Comment by EM7097** [comment]
TypeError: 'module' object is not callable
raise a new error 

```

git pull origin main
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 10 (delta 5), reused 7 (delta 2), pack-reused 0
Unpacking objects: 100% (10/10), 1.17 KiB | 19.00 KiB/s, done.
From https://github.com/ibaiGorordo/ONNX-YOLOv7-Object-Detection
 * branch            main       -> FETCH_HEAD
   a1eb903..248dab0  main       -> origin/main
Updating a1eb903..248dab0
Fast-forward
 {YOLOv7 => yolov7}/YOLOv7.py   | 0
 {YOLOv7 => yolov7}/__init__.py | 0
 {YOLOv7 => yolov7}/utils.py    | 0
 3 files changed, 0 insertions(+), 0 deletions(-)
 rename {YOLOv7 => yolov7}/YOLOv7.py (100%)
 rename {YOLOv7 => yolov7}/__init__.py (100%)
 rename {YOLOv7 => yolov7}/utils.py (100%)
(base) PS C:\Users\jjjhu\Documents\geometry\ONNX-YOLOv7-Object-Detection> python webcam_object_detection.py
Traceback (most recent call last):
  File "C:\Users\jjjhu\Documents\geometry\ONNX-YOLOv7-Object-Detection\webcam_object_detection.py", line 10, in <module>
    yolov7_detector = YOLOv7(model_path, conf_thres=0.5, iou_thres=0.5)
TypeError: 'module' object is not callable

```

**Comment by EM7097** [comment]
Oh I think this because I made "The pip yolov7 package is empty and is not what you need. The solution for this is to use "from YOLOv7...." instead of "from yolov7..." this change needs to be made in multiple places." 
Solve this error by cloning this repo again. 
And I am using a laptop with out cuda I am trying to find the right version CUDA. Thanks

**Comment by EM7097** [comment]
CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page, make sure they're in the PATH, and that your GPU is supported


Meet this error solved by   
pip uninstall onnxruntime-gpu and then pip install onnxruntime

**Comment by EM7097** [comment]
Last update: I can launch the repo for now. 
Thanks for the repo it helps a lot!  I use a 3060 and can run the small network in Inference time: 59.09 ms per frame.

**Comment by ibaiGorordo** [comment]
You might need to check the CUDA libraries setup. Ideally if you setup CUDA correctly and use onnxruntime-gpu instead of onnxruntime to run the model on the 3060, the speed should be faster.

Edit: is the 59ms on the GPU? If yes, then ignore this message

**Comment by EM7097** [comment]
I believe you are right. I think I am running this on my CPU instead of GPU. I will try to set CUDA again

**Comment by EM7097** [comment]
thanks for the information I finally set up the CUDA and right now is 12ms it is quite amazing!!!!

Thanks again for the repo and the answer to all my questions!!! you are so kind!
