### ISSUE TITLE
yolov7 export settings for use with a custom dataset

### ISSUE THREAD

**Issue by ghost** [ibaiGorordo/ONNX-YOLOv7-Object-Detection#11]
I'm trying to use this code with yolov7 trained on a custom dataset, but for some reason I can't get the boxes to line up. Works great with the models trained on the coco dataset (from pinto's model zoo) though.  

How did you export the trained yolov7 models to onnx? 

This was the command I used to export:
```bash
python export.py --weights runs/train/yolov73/weights/best.pt --grid --end2end --simplify  --topk-all 100 --iou-thres 0.65 --conf-thres 0.35 --img-size 640 480 --max-wh 640 --dynamic-batch 
```

Sorry if this is a dumb question, I'm new to yolo and onnx.

**Comment by ibaiGorordo** [comment]
If you are exporting end to end, set the argument official_nms to True. I recently added support for it, more info here: https://github.com/ibaiGorordo/ONNX-YOLOv7-Object-Detection/issues/8

**Comment by ghost** [comment]
Ok thanks, I re exported the model and tested with " --include-nms ". I still have the problem:

![Screen Shot 2022-11-29 at 9 16 40 PM](https://user-images.githubusercontent.com/60798504/204706561-7ed492ab-5182-4539-bda6-1c49a7febff8.png)

(We are using a thermal camera but the images are encoded in rgb)

It appears that it's getting the predictions correct from the model, but the bug is in drawing the boxes

**Comment by ghost** [comment]
To replicate:

## In utils.py
I changed line 4 to:
```
class_names = ['victim', 'door', 'stairs']
```
The exported model and images I used for validation can be found here:

https://github.com/keithhbova/modelAndValImages

**Comment by ibaiGorordo** [comment]
What I mean is when you create the YOLOv7 model add the `official_nms=True`. That is because there are different output formats.
yolov7_detector = YOLOv7(model_path, conf_thres=0.2, iou_thres=0.3, **official_nms=True**)

(Interesting project btw)

**Comment by ghost** [comment]
You're a king, thank you lots. 

![Screen Shot 2022-11-29 at 9 39 56 PM](https://user-images.githubusercontent.com/60798504/204709001-cdcf0773-b6ad-4637-81f3-6861ca28b4e5.png)

## For anyone from the future with the same issue:
This is my image_object_detection.py:

```python
import cv2


from yolov7 import YOLOv7

# Initialize yolov7 object detector
model_path = "models/best.onnx"
yolov7_detector = YOLOv7(model_path, conf_thres=0.2, iou_thres=0.3, official_nms=True)

frame = cv2.imread("imagesForValidation/thermal_data_01224.jpg")


cv2.imshow('frame',frame)
cv2.waitKey(0)

boxes, scores, class_ids = yolov7_detector(frame)
combined_img = yolov7_detector.draw_detections(frame)

cv2.imshow('frame',combined_img)
cv2.waitKey(0)

```

Thanks, it's a school project for assisting firefighting.
