### ISSUE TITLE
100% CPU usage while 

### ISSUE THREAD

**Issue by StefanCiobanu1989** [ibaiGorordo/ONNX-YOLOv7-Object-Detection#16]
It appears that onnxruntime-gpu is bugged or something... as while running inference the CPU goes to 100%, the only way to reduce cpu usage is to reduce the framerate of the camera to something like 5fps. Is this happening to anyone else ? 

P.S. providers seems to be  right : ['CUDAExecutionProvider', 'CPUExecutionProvider'] cuda does actually get detected by python

**Comment by ibaiGorordo** [comment]
Make sure you have CUDA properly setup with the correct compatible version: https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html
