### ISSUE TITLE
Can not run on cpu

### ISSUE THREAD

**Issue by ILG2021** [ibaiGorordo/ONNX-YOLOv7-Object-Detection#18]
When I run image_object_detection.py on cpu, it will give error:
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(float)) , expected: (tensor(float16))

change 
input_tensor = input_img[np.newaxis, :, :, :].astype(np.float32) to 
input_tensor = input_img[np.newaxis, :, :, :].astype(np.float16) will solve this problem.
So can you fix it?

**Comment by ibaiGorordo** [comment]
My guess is the issue is related on how the model was converted, i.e. float16 onnx model. Do you have the model or the script you used to convert the model?

**Comment by ILG2021** [comment]
> My guess is the issue is related on how the model was converted, i.e. float16 onnx model. Do you have the model or the script you used to convert the model?

oh. may be it is the problem.
