### ISSUE TITLE
Handling of low socre in process_output

### ISSUE THREAD

**Issue by chikako** [ibaiGorordo/ONNX-YOLOv7-Object-Detection#4]
I have a question about the processing of low score in process_output, which is a def block in yolov7.py.

About the following part:
	        
	# Filter out the objects with a low score
        predictions = predictions[obj_conf > self.conf_threshold]
        scores = scores[scores > self.conf_threshold]

I think the calculation to obtain predictions is as follows.

	predictions = predictions[**scores** > self.conf_threshold]
		                               (obj_conf -> scores)

**Comment by ibaiGorordo** [comment]
You are absolutely right, it should be scores instead of obj_conf. If you can, please submit a pull request and I will fix it.

**Comment by ibaiGorordo** [comment]
Merged. Thanks!
