### ISSUE TITLE
Only detect persons and bicycles

### ISSUE THREAD

**Issue by mahesh-gotradie** [ibaiGorordo/ONNX-YOLOv7-Object-Detection#8]
I tried with yolov7-nms-640.onnx and it detects only persons and bicycles.  
and also it doesnt draw rectangles at the correct locations. appreciate any help to resolve this
![detected_objects](https://user-images.githubusercontent.com/80161504/202654200-e9f03138-05d6-404f-bd8a-36c8faf22cdf.jpg)

**Comment by ibaiGorordo** [comment]
That is because the official NMS model had a different format than the one's from Pinto's model zoo.

I have added support for the official NMS format. You will have to set the `official_nms=True` when you initialize the YOLOv7 object: 
```
yolov7_detector = YOLOv7(model_path, conf_thres=0.2, iou_thres=0.3, official_nms=True)
```

**Comment by mahesh-gotradie** [comment]
Dear ibaiGorordo,

It worked. Thanks a lot for quick response. :)
