### ISSUE TITLE
It is crash In the NMS mode.

### ISSUE THREAD

**Issue by ptiszai** [ibaiGorordo/ONNX-YOLOv7-Object-Detection#9]
Hi,
image_object_detection.py.
Lina 8: yolov7_detector = YOLOv7(model_path, conf_thres=0.2, iou_thres=0.3, official_nms=True)
Called:
Line 19: combined_img = yolov7_detector.draw_detections(img)
Yolov7.py.
line 105:  def parse_processed_output(self, outputs):
Crash:
line 116: predictions = predictions[valid_scores, :]
IndexError: boolean index did not match indexed array along dimension 1; dimension is 6 but corresponding boolean dimension is 85
Thank
Stephen

**Comment by emrekardaslar** [comment]
I faced the same problem for yolov7-tiny onnx model and nms mods:

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by emrekardaslar** [comment]
You can use [this](https://colab.research.google.com/github/WongKinYiu/yolov7/blob/main/tools/YOLOv7onnx.ipynb#scrollTo=ipHqto0J0kkq) notebook to make a working example. I didn't tried it yet but it seems working with yolov7 nms onnx model.

**Comment by ibaiGorordo** [comment]
Hi @ptiszai @emrekardaslar Can you share the model? There is probably some case I haven't thought of that generates the error. Having the model could help me figure out the issue.

Thanks!

**Comment by emrekardaslar** [comment]
I created the model using the link I shared above. I used colab to obtain onnx model and have downloaded it.

**Comment by ibaiGorordo** [comment]
I've just tested teh tiny model from the Colab notebook and it worked fine (using `yolov7_detector = YOLOv7(model_path, conf_thres=0.2, iou_thres=0.3, official_nms=True)`). Do you get the error even without changing the image or the video link? If you change, what image/video did you use?

**Comment by emrekardaslar** [comment]
I'm out of town for couple of days, I will try to check it once I get back. Thanks for the help !

**Comment by ptiszai** [comment]
Thank.
Solved,
